### ISSUE TITLE
Docs generate is failing when a project contains a source

### ISSUE THREAD

**Issue by adamtwo** [Teradata/dbt-teradata#3]
### Describe the bug
When a project contains a source that references a different schema, `dbt generate docs` is failing with:
```
  Expected only one database in get_catalog, found [<InformationSchema INFORMATION_SCHEMA>, <InformationSchema acc_ted_con_vw.INFORMATION_SCHEMA>]
2022-01-04 13:48:49.275959 (MainThread): Traceback (most recent call last):
  File "/opt/projects/dbt/teradata/env/lib/python3.8/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/opt/projects/dbt/teradata/env/lib/python3.8/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/opt/projects/dbt/teradata/env/lib/python3.8/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/opt/projects/dbt/teradata/env/lib/python3.8/site-packages/dbt/task/generate.py", line 251, in run
    catalog_table, exceptions = adapter.get_catalog(self.manifest)
  File "/opt/projects/dbt/teradata/env/lib/python3.8/site-packages/dbt_teradata-0.19.0a0-py3.8.egg/dbt/adapters/teradata/impl.py", line 104, in get_catalog
    dbt.exceptions.raise_compiler_error(
  File "/opt/projects/dbt/teradata/env/lib/python3.8/site-packages/dbt/exceptions.py", line 435, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error
  Expected only one database in get_catalog, found [<InformationSchema INFORMATION_SCHEMA>, <InformationSchema acc_ted_con_vw.INFORMATION_SCHEMA>]
```

### Steps To Reproduce
Create a project with a source and call `dbt docs generate`.

### Expected behavior
`dbt-teradata` should support creating docs for projectsthat span multiple databases.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0
  - teradata: 0.19.0a
```

**The operating system you're using:**
MacOS

**The output of `python --version`:**
Python 3.8.12

### Additional context
I think this check in `impl.py` at line 103 is not needed. We should be able to remove it without loss of functionality. I'll do some more checks.

```
        if len(schema_map) > 1:
            dbt.exceptions.raise_compiler_error(
                f'Expected only one database in get_catalog, found '
                f'{list(schema_map)}'
            )
```

**Comment by adamtwo** [comment]
Resolved with release 0.19.0.4
